name: wechive
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  animations: ^2.0.1
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.4
  flashy_tab_bar2: ^0.0.3
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  form_field_validator: ^1.1.0
  geolocator: ^7.6.1
  get: 4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.1
  image_picker: ^0.8.4+2
  ionicons: ^0.1.2
  numeric_keyboard: ^1.0.0
  path: ^1.8.0
  pin_code_fields: ^7.3.0
  responsive_framework: ^0.1.4
  twitter_login: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
